import { useMemo, useState } from 'react'
import ModuleShell from '../ModuleShell.jsx'

const warningMessages = [
  { id: 'parcel', device: 'ios', sender: 'MetroPost Delivery', meta: 'Unknown mobile • +61 418 440 291', messages: ['We attempted delivery of parcel MP-482901.', 'Pay the $2.15 redelivery fee before 10:00 AM.', 'metropost-redelivery.example/MP482901'], clues: { meta: 'An organisation contacting you from an unfamiliar mobile number deserves scrutiny.', 1: 'A small fee can lead to a fake payment page that steals card details.', 2: 'The unexpected address should not be trusted. Open the courier app independently.' } },
  { id: 'bank', device: 'android', sender: 'Harbour Bank', meta: 'Sender name shown • identity not guaranteed', messages: ['$1,280 transfer to A. Patel is pending.', 'Call our new security line: 07 5550 0188.', 'Keep your verification code ready for the fraud officer.'], clues: { meta: 'Caller and sender names can be spoofed.', 0: 'Fear about a large transfer is used to create urgency.', 2: 'A bank should never ask for a one-time security code.' } },
  { id: 'reward', device: 'pixel', sender: 'Rewards Centre', meta: 'Today 1:18 PM • Unknown sender', messages: ['Congrats! Your number won a $750 shopping reward.', 'Only 3 claims remain. Confirm your details now.', 'reward-claim-now.example/winner'], clues: { meta: 'An unexpected prize from an unknown sender has no trusted context.', 1: 'Scarcity is used to stop you thinking carefully.', 2: 'The claim link uses an unrelated, unverified domain.' } },
  { id: 'it', device: 'samsung', sender: 'Solstice IT Support', meta: 'External SMS • not a service-desk channel', messages: ['Hi Jordan, we are repairing today’s sign-in outage.', 'Approve the next authenticator prompt.', 'Do not create another ticket—it will slow the repair.'], clues: { meta: 'Internal support should use approved company channels.', 1: 'Approving an unexpected prompt can give an attacker access.', 2: 'Discouraging the official process prevents verification.' } },
  { id: 'tax', device: 'compact', sender: 'Revenue Refund', meta: 'Unknown sender • 6:44 PM', messages: ['Your $436.20 tax refund could not be deposited.', 'Update your bank details before midnight.', 'revenue-refund-au.example/secure'], clues: { meta: 'The contact was not expected and arrives outside normal context.', 0: 'An unexpected refund uses excitement to lower caution.', 2: 'Government services should be opened through their known portal, not an SMS link.' } },
]

const manipulationCases = [
  { id: 'urgency', text: 'Act in 15 minutes or your company mailbox will be permanently disabled.', correct: 'urgency', options: ['Urgency', 'Authority', 'Curiosity', 'Social proof'], explanation: 'A forced deadline reduces the time available to verify the request.' },
  { id: 'authority', text: 'CEO Marcus asked me to contact you. Keep this confidential and buy the cards now.', correct: 'authority', options: ['Reward', 'Authority', 'Convenience', 'Familiarity'], explanation: 'The message borrows senior authority and adds secrecy to discourage questions.' },
  { id: 'fear', text: 'A $2,400 transfer is leaving your account. Call immediately with your security code.', correct: 'fear', options: ['Fear', 'Friendship', 'Curiosity', 'Routine'], explanation: 'A frightening financial event pushes the recipient toward the attacker’s contact path.' },
  { id: 'reward', text: 'You have won a $750 reward. Only three claims remain—verify your card to collect it.', correct: 'reward', options: ['Authority', 'Fear', 'Reward', 'Helpfulness'], explanation: 'An unexpected reward combines excitement with scarcity and a sensitive request.' },
]

const safeResponseCases = [
  { id: 'delivery', sender: 'MetroPost', messages: ['Parcel MP-482901 could not be delivered.', 'Pay $2.15 before 10:00 AM: metropost-redelivery.example'], correct: 4, options: ['Compare the visible spelling, then open the link if it looks correct', 'Reply with the company address and request proof', 'Forward the SMS to Facilities and ask them to pay', 'Search the courier and call the first result', 'Open the known courier app or type its official site yourself', 'Wait for another message before checking'], explanation: 'Leaving the SMS and checking an independently opened service breaks the untrusted path.' },
  { id: 'bank', sender: 'Harbour Bank', messages: ['$1,280 transfer pending.', 'Call 07 5550 0188 and keep your code ready.'], correct: 2, options: ['Call the supplied number but refuse to share the code', 'Reply that the transfer is unauthorised', 'Use the known banking app or number printed on the card', 'Search the supplied number and trust it if no warning appears', 'Wait for a second alert', 'Ask a colleague if they received the same text'], explanation: 'Verify the alert without relying on any contact detail supplied by the suspicious message.' },
  { id: 'it', sender: 'Solstice IT', messages: ['Approve the next authentication prompt.', 'Do not create another support ticket.'], correct: 5, options: ['Approve it, then inspect the location', 'Ask the sender for a ticket number by SMS', 'Approve only if an outage was announced', 'Ignore it and continue working', 'Send a screenshot with the code covered', 'Deny it and contact IT through the official portal'], explanation: 'An unrequested authentication prompt should be denied and reported through the normal channel.' },
  { id: 'clicked', sender: 'CloudDesk', messages: ['Protected document: clouddesk-access.example', 'You already entered your work password.'], correct: 3, options: ['Delete the message and monitor the account', 'Change the password but report only if misuse occurs', 'Turn off the phone and wait until tomorrow', 'Report immediately and follow the company recovery process', 'Call the support number in the SMS', 'Reopen the page to test whether the password worked'], explanation: 'Prompt reporting lets the organisation revoke sessions and contain the incident.' },
]

function PhoneMessage({ example, found = new Set(), onClue }) {
  return <article className={`sms-phone ${example.device}`}><div className="phone-status"><span>9:41</span><span>▮▮ ◔</span></div><header><button type="button">‹</button><span>●</span><div><strong>{example.sender}</strong><button className={found.has(`${example.id}-meta`) ? 'found' : ''} type="button" onClick={() => onClue?.(`${example.id}-meta`)}>{example.meta}</button></div></header><div className="sms-thread">{example.messages.map((message, index) => <button className={`${index === example.messages.length - 1 ? 'link' : ''} ${found.has(`${example.id}-${index}`) ? 'found' : ''}`} type="button" key={message} onClick={() => onClue?.(`${example.id}-${index}`)}>{message}</button>)}</div><footer>Message&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;＋</footer></article>
}

export default function SmsPhishingModule({ onClose, onComplete, completed = false }) {
  const [step, setStep] = useState(0)
  const [found, setFound] = useState(() => new Set())
  const [manipulationAnswers, setManipulationAnswers] = useState({})
  const [responseAnswers, setResponseAnswers] = useState({})
  const totalClues = warningMessages.reduce((total, item) => total + Object.keys(item.clues).length, 0)
  const manipulationComplete = manipulationCases.every((item) => manipulationAnswers[item.id] === item.correct)
  const responsesComplete = safeResponseCases.every((item) => responseAnswers[item.id] === item.correct)
  const canContinue = step === 0 ? found.size === totalClues : step === 1 ? manipulationComplete : step === 2 ? responsesComplete : true

  const discoveries = useMemo(() => warningMessages.flatMap((item) => Object.entries(item.clues).map(([key, text]) => ({ id: `${item.id}-${key}`, text }))), [])
  const reveal = (id) => {
    if (!discoveries.some((item) => item.id === id)) return
    setFound((current) => new Set(current).add(id))
  }
  const continueModule = () => {
    if (step < 3) setStep((current) => current + 1)
    else if (!completed) onComplete()
    else onClose()
  }

  return <ModuleShell moduleId="sms" title="SMS PHISHING AWARENESS" kicker="UNIVERSAL TRAINING MODULE // SMS PHISHING" steps={['SPOT THE SIGNS', 'BREAK THE MANIPULATION', 'SAFE RESPONSE', 'SUMMARY']} step={step} canContinue={canContinue} onContinue={continueModule} onClose={onClose} completed={completed}>
    {step === 0 && <div className="training-stage"><div className="stage-intro purple"><div><span>STEP 1 // FIVE MESSAGE STYLES</span><h3>Spot the signs</h3><p>Select suspicious details in each mobile message. Orange clues turn green when inspected.</p></div><strong>{found.size} / {totalClues}<small>SIGNS FOUND</small></strong></div><div className="phone-grid">{warningMessages.map((item) => <PhoneMessage example={item} key={item.id} found={found} onClue={reveal} />)}</div><div className="discovery-list">{discoveries.filter((item) => found.has(item.id)).map((item) => <p key={item.id}><span>✓</span>{item.text}</p>)}</div></div>}

    {step === 1 && <div className="training-stage"><div className="stage-intro purple"><div><span>STEP 2 // PSYCHOLOGICAL PRESSURE</span><h3>Break the manipulation</h3><p>Name the tactic being used. Recognising the emotional trigger creates time to verify.</p></div><strong>{Object.keys(manipulationAnswers).length} / 4<small>TACTICS</small></strong></div><div className="manipulation-grid">{manipulationCases.map((item) => <article key={item.id}><blockquote>“{item.text}”</blockquote><div>{item.options.map((option) => <button className={manipulationAnswers[item.id] === option.toLowerCase() ? 'selected' : ''} type="button" key={option} onClick={() => setManipulationAnswers((current) => ({ ...current, [item.id]: option.toLowerCase() }))}>{option}</button>)}</div>{manipulationAnswers[item.id] && <p className={manipulationAnswers[item.id] === item.correct ? 'correct-note' : 'wrong-note'}>{manipulationAnswers[item.id] === item.correct ? '✓ ' : 'Try again. '}{item.explanation}</p>}</article>)}</div></div>}

    {step === 2 && <div className="training-stage"><div className="stage-intro purple"><div><span>STEP 3 // DECIDE OUTSIDE THE MESSAGE</span><h3>Choose the safe response</h3><p>Read each mobile conversation and choose the strongest response from six realistic options.</p></div><strong>{Object.keys(responseAnswers).length} / 4<small>SCENARIOS</small></strong></div>{safeResponseCases.map((item) => <article className="safe-response-case" key={item.id}><PhoneMessage example={{ ...item, id: item.id, device: 'ios', meta: 'Incoming SMS' }} /><div><h4>What should you do next?</h4><div className="six-options">{item.options.map((option, index) => <button className={`${responseAnswers[item.id] === index ? 'selected' : ''} ${responseAnswers[item.id] !== undefined && index === item.correct ? 'correct' : ''}`} type="button" key={option} onClick={() => setResponseAnswers((current) => ({ ...current, [item.id]: index }))}><span>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div>{responseAnswers[item.id] !== undefined && <p className={responseAnswers[item.id] === item.correct ? 'correct-note' : 'wrong-note'}>{responseAnswers[item.id] === item.correct ? '✓ Correct. ' : 'Not the safest route. '}{item.explanation}</p>}</div></article>)}</div>}

    {step === 3 && <div className="training-stage summary-stage purple-summary"><span className="summary-shield">▤</span><h3>Stop the message controlling the next step.</h3><p>SMS phishing succeeds when a short message creates enough urgency, fear, authority or excitement to move you into an attacker-controlled link, phone number or conversation.</p><div className="summary-grid"><div><strong>DO NOT TRUST THE THREAD</strong><p>Sender names and familiar conversations are not proof of identity.</p></div><div><strong>LEAVE THE SMS</strong><p>Use a known app, saved bookmark or independently sourced number.</p></div><div><strong>PROTECT CODES</strong><p>Never share authentication codes or approve prompts you did not start.</p></div><div><strong>REPORT FAST</strong><p>If you interacted, tell the organisation immediately so access can be secured.</p></div></div></div>}
  </ModuleShell>
}
